 image: docker:latest
services:
  - docker:dind

stages:
  - install
  
variables:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  IMAGE: "danilodesousa/elastic-boot"

cache:
  paths:
    - .m2/repository

install:jdk8:
  stage: install
  script:
    - mvn clean install -U -DskipTests  
  only:
    - master
  image: maven:3.3.9-jdk-8
  artifacts:
    paths:
     - target/*.jar
